apiVersion: v1
kind: Service
metadata:
  name: kube-insight-kairosdb
  namespace: {{ .Values.namespace }}
  labels:
    kubernetes.io/cluster-service: "true"
    task: "kube-insight-kairosdb"
    kubernetes.io/name: "kube-insight-kairosdb"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    k8s-app: kube-insight-kairosdb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-insight-kairosdb
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: "kube-insight-kairosdb"
    kubernetes.io/cluster-service: "true"
    version: "{{ .Values.kairosdb.version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-insight-kairosdb
      version: "{{ .Values.kairosdb.version }}"
  template:
    metadata:
      labels:
        task: "kube-insight-kairosdb"
        k8s-app: "kube-insight-kairosdb"
        version: "{{ .Values.kairosdb.version }}"
    spec:
      containers:
      - name: kube-insight-kairosdb
        image: {{ .Values.kairosdb.image }}:{{ .Values.kairosdb.version }}
        imagePullPolicy: {{ .Values.kairosdb.pullPolicy }}
        env:
        - name: CASSANDRA_HOSTS
          value: kube-insight-cassandra.{{ .Values.namespace }}.svc.cluster.local
        - name: CASSANDRA_PORT
          value: "9042"
        - name: CASSANDRA_READ_CONSISTENCY_LEVEL
          value: "{{ .Values.kairosdb.cassandraReadConsistencyLevel }}"
        - name: CASSANDRA_WRITE_CONSISTENCY_LEVEL
          value: "{{ .Values.kairosdb.cassandraWriteConsistencyLevel }}"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /api/v1/health/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/v1/health/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: {{ .Values.kairosdb.cpuLimitMilliCores }}m
            memory: {{ .Values.kairosdb.memLimitMB }}Mi
          requests:
            cpu: {{ .Values.kairosdb.cpuRequestMilliCores }}m
            memory: {{ .Values.kairosdb.memRequestMB }}Mi
      tolerations:
      # allow scheduling onto master
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
