#
# Manifest inspired by:
#  https://github.com/fluent/fluent-bit-kubernetes-logging/tree/master/output/kafka
#
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: "fluent-bit-logging"
    version: "{{ .Values.fluentbit.version }}"
    kubernetes.io/cluster-service: "true"
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: "fluent-bit-logging"
        version: "{{ .Values.fluentbit.version }}"
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit
        image: {{ .Values.fluentbit.image }}:{{ .Values.fluentbit.version }}
        imagePullPolicy: Always
        env:
        - name:  HTTP_HOST
          value: "{{ .Values.kubeInsightLogServer.host }}"
        - name:  HTTP_PORT
          value: "{{ .Values.kubeInsightLogServer.port }}"
        - name:  HTTP_URI
          value: "/write"
        command:
          - /fluent-bit/bin/fluent-bit
          - -c
          - /fluent-bit/etc/fluent-bit.conf
        ports:
        - containerPort: 2020
        readinessProbe:
          httpGet:
            path: /api/v1/metrics/prometheus
            port: 2020
        livenessProbe:
          httpGet:
            path: /
            port: 2020
        resources:
          limits:
            cpu: {{ .Values.fluentbit.cpuLimitMilliCores }}m
            memory: {{ .Values.fluentbit.memLimitMB }}Mi
          requests:
            cpu: {{ .Values.fluentbit.cpuRequestMilliCores }}m
            memory: {{ .Values.fluentbit.memRequestMB }}Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
