apiVersion: v1
kind: Service
metadata:
  name: kube-insight-prometheus-kairosdb-adapter
  namespace: {{ .Values.namespace }}
  labels:
    kubernetes.io/cluster-service: "true"
    task: "kube-insight-prometheus-kairosdb-adapter"
    kubernetes.io/name: "kube-insight-prometheus-kairosdb-adapter"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9201
    targetPort: 9201
  selector:
    k8s-app: kube-insight-prometheus-kairosdb-adapter

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-insight-prometheus-kairosdb-adapter
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: "kube-insight-prometheus-kairosdb-adapter"
    kubernetes.io/cluster-service: "true"
    version: "{{ .Values.prometheusKairosDBAdapter.version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-insight-prometheus-kairosdb-adapter
      version: {{ .Values.prometheusKairosDBAdapter.version }}
  template:
    metadata:
      labels:
        task: "kube-insight-prometheus-kairosdb-adapter"
        k8s-app: "kube-insight-prometheus-kairosdb-adapter"
        version: "{{ .Values.prometheusKairosDBAdapter.version }}"
    spec:
      containers:
      - name: kube-insight-prometheus-kairosdb-adapter
        image: {{ .Values.prometheusKairosDBAdapter.image }}:{{ .Values.prometheusKairosDBAdapter.version }}
        imagePullPolicy: {{ .Values.prometheusKairosDBAdapter.pullPolicy }}
        args:
          - --config=/etc/prometheus-kairosdb-adapter/config.yml 
        ports:
        - name: http
          containerPort: 9201
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus-kairosdb-adapter
          readOnly: true          
        resources:
          limits:
            cpu: {{ .Values.prometheusKairosDBAdapter.cpuLimitMilliCores }}m
            memory: {{ .Values.prometheusKairosDBAdapter.memLimitMB }}Mi
          requests:
            cpu: {{ .Values.prometheusKairosDBAdapter.cpuRequestMilliCores }}m
            memory: {{ .Values.prometheusKairosDBAdapter.memRequestMB }}Mi
      volumes:
      - name: config
        configMap:
          name: prometheus-kairosdb-adapter-config
      tolerations:
      # allow scheduling onto master
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
