apiVersion: v1
kind: Service
metadata:
  name: kube-insight-cassandra
  namespace: {{ .Values.namespace }}
  labels:
    kubernetes.io/cluster-service: "true"
    task: "kube-insight-cassandra"
    kubernetes.io/name: "kube-insight-cassandra"
spec:
  type: ClusterIP
  ports:
  - name: cql
    port: 9042
    targetPort: 9042
  - name: intra
    port: 7000
    targetPort: 7000
  - name: tls
    port: 7001
    targetPort: 7001
  - name: jmx
    port: 7199
    targetPort: 7199
  selector:
    k8s-app: kube-insight-cassandra

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kube-insight-cassandra
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: kube-insight-cassandra
    kubernetes.io/cluster-service: "true"
    version: "{{ .Values.cassandra.version }}"
spec:
  serviceName: kube-insight-cassandra
  replicas: {{ .Values.cassandra.replicas }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: kube-insight-cassandra
        version: "{{ .Values.cassandra.version }}"
    spec:
      containers:
      - name: kube-insight-cassandra
        image: "{{ .Values.cassandra.image }}:{{ .Values.cassandra.version }}"
        imagePullPolicy: {{ .Values.cassandra.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.cassandra.cpuLimitMilliCores }}m
            memory: {{ .Values.cassandra.memLimitMB }}Mi
          requests:
            cpu: {{ .Values.cassandra.cpuRequestMilliCores }}m
            memory: {{ .Values.cassandra.memRequestMB }}Mi	
        env:
        # TODO: add CASSANDRA_SEEDS (see https://github.com/kubernetes/charts/blob/master/incubator/cassandra/templates/cassandra-statefulset.yaml)
        # TODO: add MAX_HEAP_SIZE
        - name: CASSANDRA_CLUSTER_NAME
          value: kube-insight-cassandra
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: [ "/bin/sh", "-c", "nodetool status" ]
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          exec:
            command: [ "/bin/sh", "-c", "nodetool status | grep -E \"^UN\\s+${POD_IP}\"" ]
          initialDelaySeconds: 90
          periodSeconds: 30
        ports:
        - name: intra
          containerPort: 7000
        - name: tls
          containerPort: 7001
        - name: jmx
          containerPort: 7199
        - name: cql
          containerPort: 9042
        volumeMounts:
        - name: data
          mountPath: /var/lib/cassandra
      terminationGracePeriodSeconds: 30
      # TODO: volume claim
      volumes:
      - name: data
        emptyDir: {}
# TODO: tolerate master taint?
