kind: Service
apiVersion: v1
metadata:
  name: kube-insight-grafana-nodeport
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    k8s-app: kube-insight-grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
