#
# See https://github.com/kubernetes/charts/blob/master/stable/prometheus-node-exporter
#

apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: node-exporter
    k8s-app: node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
    spec:
      serviceAccountName: node-exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      hostNetwork: true
      hostPID: true
      containers:
      - name: node-exporter
        image: {{ .Values.nodeExporter.image }}:{{ .Values.nodeExporter.version }}
        imagePullPolicy: {{ .Values.nodeExporter.pullPolicy }}
        args:
        - "--web.listen-address=:9100"
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"
        ports:
        - name: metrics
          containerPort: 9100
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 9100
        readinessProbe:
          httpGet:
            path: /
            port: 9100
        resources:
          limits:
            cpu: {{ .Values.nodeExporter.cpuLimitMilliCores }}m
            memory: {{ .Values.nodeExporter.memLimitMB }}Mi
          requests:
            cpu: {{ .Values.nodeExporter.cpuRequestMilliCores }}m
            memory: {{ .Values.nodeExporter.memRequestMB }}M
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
      tolerations:
        # allow scheduling onto any node
        - effect: NoSchedule
          operator: Exists
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
