apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    protocol: TCP
    nodePort: 30090
  selector:
    app: prometheus
